name: Sentry Release Notifier

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(jq -r .version package.json)"

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        with:
          version: ${{ steps.get_version.outputs.version }}
          sentry_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          org: jens-astrup
          project: aces-of-spades

      - name: Deploy to Staging
        if: github.event_name == 'pull_request'
        run: echo "Deploying to staging environment..."

      - name: Deploy to Production
        if: github.event_name == 'push'
        run: |
          echo "Deploying to production environment..."
          npm run deploy
