name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters:
            relevant:
              - 'src/**'
              - 'yarn.lock'

      - name: Skip tests
        if: steps.filter.outputs.relevant == 'false'
        run: echo "No changes in src/ or yarn.lock. Skipping tests."

      - name: Set up Node.js
        if: steps.filter.outputs.relevant == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        if: steps.filter.outputs.relevant == 'true'
        run: yarn install --frozen-lockfile

      - name: Run tests
        if: steps.filter.outputs.relevant == 'true'
        run: yarn test:coverage

      - name: Upload coverage reports to Codecov
        if: steps.filter.outputs.relevant == 'true'
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: JensAstrup/aces-frontend
